type Mutation {
    deactivateUser(user: UserInput!): Int
    activateUser(user: UserInput!): Int

    makeAdminUser(user: UserInput!): Int
    removeAdminUser(user: UserInput!): Int

    removeUser(user: UserInput!): Int
}