
export const cons = {
    studentsCSVPath: 'src/files/students.csv',
    studentsIds: 'src/files/students_id.csv',
    downloadKey: 'dasiou938xec0u9999pcaskdc30cru94m9uoacoer7ic3',

    formNames : [
        'studentId',
        'title',
        'authors',
        'translatedAuthors',
        'startPage',
        'endPage',
        'articleNumber',
        'doi',
        'conferenceTitle',
        'hierarchyDomains',
        'internationalMagazine',
        'BDI',
        'bdiType',
        'nonBDI',
        'thesisType',
        'doctoralThesisType',
        'national',
        'international',
        'bdiDatabase',
        'cncsRecognition',
        'quality',
        'manifestationClassification',
        'manifestationType',
        'magazineType',
        'link',
        'year',
        'volume',
        'number',
        'magazineName',
        'magazineISI',
        'bookTitle',
        'bookPages',
        'edition',
        'isbn',
        'observations',
        'chapterName',
        'qualityStandard',
        'country',
        'translatedChapters',
        'manifestationName',
        'cbi',
        'patentNumber',
        'authority',
        'contactName',
        'projectCode',
        'financier',
        'function',
        'sourceTitle',
        'issue',
        'citations',
        'yearOfAward',
        'name',
        'awardName',
        'awardOrganization',
        'yearOfActivity',
        'admissionYear',
        'academyName',
        'memberType',
        'committeeName',
        'committeeYear',
        'place',
        'contact',
        'date',
        'startDate',
        'endDate',
    ]
}
