type Mutation {
    getInformation(authToken: AuthTokenInput!): [Information]
    updateInformation(authToken: AuthTokenInput!, data: InformationInput!): Int
    deleteInformation(authToken: AuthTokenInput!): Int

    getScientificArticleISI(authToken: AuthTokenInput!): [ScientificArticleISI]
    updateScientificArticleISI(authToken: AuthTokenInput!, data: ScientificArticleISIInput!): Int
    deleteScientificArticleISI(authToken: AuthTokenInput!): Int

    getISIProceeding(authToken: AuthTokenInput!): [ISIProceeding]
    updateISIProceeding(authToken: AuthTokenInput!, data:ISIProceedingInput!): Int
    deleteISIProceeding(authToken: AuthTokenInput!): Int

    getScientificArticleBDI(authToken: AuthTokenInput!): [ScientificArticleBDI]
    updateScientificArticleBDI(authToken: AuthTokenInput!, data: ScientificArticleBDIInput!): Int
    deleteScientificArticleBDI(authToken: AuthTokenInput!): Int

    getScientificBook(authToken: AuthTokenInput!): [ScientificBook]
    updateScientificBook(authToken: AuthTokenInput!, data: ScientificBookInput!): Int
    deleteScientificBook(authToken: AuthTokenInput!): Int

    getTranslation(authToken: AuthTokenInput!): [Translation]
    updateTranslation(authToken: AuthTokenInput!, data: TranslationInput!): Int
    deleteTranslation(authToken: AuthTokenInput!): Int

    getScientificCommunication(authToken: AuthTokenInput!): [ScientificCommunication]
    updateScientificCommunication(authToken: AuthTokenInput!, data: ScientificCommunicationInput!): Int
    deleteScientificCommunication(authToken: AuthTokenInput!): Int

    getPatent(authToken: AuthTokenInput!): [Patent]
    updatePatent(authToken: AuthTokenInput!, data: PatentInput!): Int
    deletePatent(authToken: AuthTokenInput!): Int

    getResearchContract(authToken: AuthTokenInput!): [ResearchContract]
    updateResearchContract(authToken: AuthTokenInput!, data: ResearchContractInput!): Int
    deleteResearchContract(authToken: AuthTokenInput!): Int

    getCitation(authToken: AuthTokenInput!): [Citation]
    updateCitation(authToken: AuthTokenInput!, data: CitationInput!): Int
    deleteCitation(authToken: AuthTokenInput!): Int

    getAwardAndNomination(authToken: AuthTokenInput!): [AwardAndNomination]
    updateAwardAndNomination(authToken: AuthTokenInput!, data: AwardAndNominationInput!): Int
    deleteAwardAndNomination(authToken: AuthTokenInput!): Int

    getAcademyMember(authToken: AuthTokenInput!): [AcademyMember]
    updateAcademyMember(authToken: AuthTokenInput!, data: AcademyMemberInput!): Int
    deleteAcademyMember(authToken: AuthTokenInput!): Int

    getEditorialMember(authToken: AuthTokenInput!): [EditorialMember]
    updateEditorialMember(authToken: AuthTokenInput!, data: EditorialMemberInput!): Int
    deleteEditorialMember(authToken: AuthTokenInput!): Int

    getOrganizedEvent(authToken: AuthTokenInput!): [OrganizedEvent]
    updateOrganizedEvent(authToken: AuthTokenInput!, data: OrganizedEventInput!): Int
    deleteOrganizedEvent(authToken: AuthTokenInput!): Int

    getWithoutActivity(authToken: AuthTokenInput!): [WithoutActivity]
    updateWithoutActivity(authToken: AuthTokenInput!, data: WithoutActivityInput!): Int
    deleteWithoutActivity(authToken: AuthTokenInput!): Int

    getDidacticActivity(authToken: AuthTokenInput!): [DidacticActivity]
    updateDidacticActivity(authToken: AuthTokenInput!, data: DidacticActivityInput!): Int
    deleteDidacticActivity(authToken: AuthTokenInput!): Int

}