# ----------========== Data Types ==========---------- #
scalar Date

# ----------========== Type ==========---------- #
interface GenericForm {
    id: Int
    type: Int
}

# ----------========== Type ==========---------- #

type GqlResponse {
    message: String
}

type Id {
    id: Int!
    identifier: String!
    fullName: String!

    activated: Boolean
}

type User {
    id: Int
    identifier: String!
    email: String!
    admin: Boolean!
    activated: Boolean!
    updated: Date!
}

type AuthToken {
    token: String!
}

type Information implements GenericForm {
    id: Int!
    fullName: String!
    marriageName: String!
    thesisCoordinator: String!
    founding: String!
    completionDate: Date!
    owner: Int!
    updated: Date!
    type: Int!
}

type ScientificArticleISI implements GenericForm {
    id: Int!
    articleTitle: String!
    authors: String!
    publicationDate: Date!
    volume: String!
    issue: String!
    startingPage: Int!
    endingPage: Int!
    impactFactor: String!
    cnatdcuClassification: String!
    doi: String!
    conferenceName: String!
    observations: String!
    owner: Int!
    updated: Date!
    type: Int!
}

type ISIProceeding implements GenericForm {
    id: Int!
    articleTitle: String!
    authors: String!
    conferenceName: String!
    indexedVolumeType: String!
    publicationYear: Int!
    articleType: String!
    conferenceType: String!
    conferenceLink: String!
    startingPage: Int!
    endingPage: Int!
    observations: String!
    owner: Int!
    updated: Date!
    type: Int!
}

type ScientificArticleBDI implements GenericForm {
    id: Int!
    hierarchyDomains: String!
    articleTitle: String!
    authors: String!
    bdiIndexedMagazine: String!
    publicationYear: Int!
    volume: String!
    number: Int!
    startingPage: Int!
    endingPage: Int!
    internationalMagazine: String!
    cnatdcuClassification: String!
    indexedArticleLink: String!
    bdiDatabase: String!
    bdiDatabaseLink: String!
    observations: String!
    owner: Int!
    updated: Date!
    type: Int!
}

type ScientificBook implements GenericForm {
    id: Int!
    hierarchyDomains: String!
    chapterTitle: String!
    authors: String!
    bookTitle: String!
    pageNumber: Int!
    publicationYear: Int!
    publishingHouse: String!
    publicationType: String!
    isbn: String!
    observations: String!
    owner: Int!
    updated: Date!
    type: Int!
}

type Translation implements GenericForm {
    id: Int!
    hierarchyDomains: String!
    translationTitle: String!
    authors: String!
    translatedAuthors: String!
    publicationYear: Int!
    publishingHouse: String!
    country: String!
    pageNumber: Int!
    isbn: String!
    translationType: String!
    observations: String!
    owner: Int!
    updated: Date!
    type: Int!
}

type ScientificCommunication implements GenericForm {
    id: Int!
    authors: String!
    communicationType: String!
    presentationYear: Int!
    scientificManifestationName: String!
    manifestationType: String!
    scientificManifestationLink: String!
    observations: String!
    owner: Int!
    updated: Date!
    type: Int!
}

type Patent implements GenericForm {
    id: Int!
    patentTitleOrCBI: String!
    authors: String!
    yearOfObtainingPatent: Int!
    patentNumber: Int!
    patentType: String!
    authority: String!
    country: String!
    observations: String!
    owner: Int!
    updated: Date!
    type: Int!
}

type ResearchContract implements GenericForm {
    id: Int!
    researchContractNameOrProject: String!
    projectCode: String!
    financier: String!
    function: String!
    startProjectPeriod: Date!
    endProjectPeriod: Date!
    contractType: String!
    observations: String!
    owner: Int!
    updated: Date!
    type: Int!
}

type Citation implements GenericForm {
    id: Int!
    articleTitle: String!
    authors: String!
    publicationTitleWhereReferenced: String!
    authorsNamesThatReference: String!
    citationYear: Int!
    volume: String!
    impactFactor: String!
    issue: String!
    articleNumber: Int!
    startingPage: Int!
    endingPage: Int!
    doi: String!
    cnatdcuClassification: String!
    citations: String!
    observations: String!
    owner: Int!
    updated: Date!
    type: Int!
}

type AwardAndNomination implements GenericForm {
    id: Int!
    yearOfAward: Int!
    awardName: String!
    awardType: String!
    organizationThatGiveTheAward: String!
    country: String!
    awardedFor: String!
    observations: String!
    owner: Int!
    updated: Date!
    type: Int!
}

type AcademyMember implements GenericForm {
    id: Int!
    admissionYear: Int!
    academyName: String!
    memberType: String!
    observations: String!
    owner: Int!
    updated: Date!
    type: Int!
}

type EditorialMember implements GenericForm {
    id: Int!
    committeeName: String!
    magazineName: String!
    yearOfCommitteeAttendance: Int!
    quality: String!
    magazineType: String!
    nationalOrInternational: String!
    observations: String!
    owner: Int!
    updated: Date!
    type: Int!
}

type OrganizedEvent implements GenericForm {
    id: Int!
    manifestationName: String!
    startDate: Date!
    endDate: Date!
    manifestationPlace: String!
    manifestationType: String!
    manifestationClassification: String!
    manifestationLink: String!
    contactPerson: String!
    observations: String!
    owner: Int!
    updated: Date!
    type: Int!
}

type WithoutActivity implements GenericForm {
    id: Int!
    observations: String!
    owner: Int!
    updated: Date!
    type: Int!
}

type DidacticActivity implements GenericForm {
    id: Int!
    className: String!
    activityType: String!
    yearOfAttendingActivity: Int!
    owner: Int!
    updated: Date!
    type: Int!
}

# ----------========== Input Types ==========---------- #

input IdInput {
    id: Int
    identifier: String!
    fullName: String!
}

input BaseUser {
    identifier: String!
    email: String!
}

input UserInput {
    id: Int!
    identifier: String!
    email: String!
    admin: Boolean
    activated: Boolean
}

input AuthTokenInput {
    token: String!
}

input InformationInput {
    id: Int
    fullName: String
    marriageName: String
    thesisCoordinator: String
    founding: String
    completionDate: Date
    type: Int
    
    updated: Date
    owner: Int
}

input ScientificArticleISIInput {
    id: Int
    articleTitle: String
    authors: String
    publicationDate: Date
    volume: String
    issue: String
    startingPage: Int
    endingPage: Int
    impactFactor: String
    cnatdcuClassification: String
    doi: String
    conferenceName: String
    observations: String
    type: Int

    updated: Date
    owner: Int
}

input ISIProceedingInput {
    id: Int
    articleTitle: String
    authors: String
    conferenceName: String
    indexedVolumeType: String
    publicationYear: Int
    articleType: String
    conferenceType: String
    conferenceLink: String
    startingPage: Int
    endingPage: Int
    observations: String
    type: Int

    updated: Date
    owner: Int
}

input ScientificArticleBDIInput {
    id: Int
    hierarchyDomains: String
    articleTitle: String
    authors: String
    bdiIndexedMagazine: String
    publicationYear: Int
    volume: String
    number: Int
    startingPage: Int
    endingPage: Int
    internationalMagazine: String
    cnatdcuClassification: String
    indexedArticleLink: String
    bdiDatabase: String
    bdiDatabaseLink: String
    observations: String
    type: Int

    updated: Date
    owner: Int
}

input ScientificBookInput {
    id: Int
    hierarchyDomains: String
    chapterTitle: String
    authors: String
    bookTitle: String
    pageNumber: Int
    publicationYear: Int
    publishingHouse: String
    publicationType: String
    isbn: String
    observations: String
    type: Int

    updated: Date
    owner: Int
}

input TranslationInput {
    id: Int
    hierarchyDomains: String
    translationTitle: String
    authors: String
    translatedAuthors: String
    publicationYear: Int
    publishingHouse: String
    country: String
    pageNumber: Int
    isbn: String
    translationType: String
    observations: String
    type: Int

    updated: Date
    owner: Int
}

input ScientificCommunicationInput {
    id: Int
    authors: String
    communicationType: String
    presentationYear: Int
    scientificManifestationName: String
    manifestationType: String
    scientificManifestationLink: String
    observations: String
    type: Int

    updated: Date
    owner: Int
}

input PatentInput {
    id: Int
    patentTitleOrCBI: String
    authors: String
    yearOfObtainingPatent: Int
    patentNumber: Int
    patentType: String
    authority: String
    country: String
    observations: String
    type: Int

    updated: Date
    owner: Int
}

input ResearchContractInput {
    id: Int
    researchContractNameOrProject: String
    projectCode: String
    financier: String
    function: String
    startProjectPeriod: Date
    endProjectPeriod: Date
    contractType: String
    observations: String
    type: Int

    updated: Date
    owner: Int
}

input CitationInput {
    id: Int
    articleTitle: String
    authors: String
    publicationTitleWhereReferenced: String
    authorsNamesThatReference: String
    citationYear: Int
    volume: String
    impactFactor: String
    issue: String
    articleNumber: Int
    startingPage: Int
    endingPage: Int
    doi: String
    cnatdcuClassification: String
    citations: String
    observations: String
    type: Int

    updated: Date
    owner: Int
}

input AwardAndNominationInput {
    id: Int
    yearOfAward: Int
    awardName: String
    awardType: String
    organizationThatGiveTheAward: String
    country: String
    awardedFor: String
    observations: String
    type: Int

    updated: Date
    owner: Int
}

input AcademyMemberInput {
    id: Int
    admissionYear: Int
    academyName: String
    memberType: String
    observations: String
    type: Int

    updated: Date
    owner: Int
}

input EditorialMemberInput {
    id: Int
    committeeName: String
    magazineName: String
    yearOfCommitteeAttendance: Int
    quality: String
    magazineType: String
    nationalOrInternational: String
    observations: String
    type: Int

    updated: Date
    owner: Int
}

input OrganizedEventInput {
    id: Int
    manifestationName: String
    startDate: Date
    endDate: Date
    manifestationPlace: String
    manifestationType: String
    manifestationClassification: String
    manifestationLink: String
    contactPerson: String
    observations: String
    type: Int

    updated: Date
    owner: Int
}

input WithoutActivityInput {
    id: Int
    observations: String
    type: Int

    updated: Date
    owner: Int
}

input DidacticActivityInput {
    id: Int
    className: String
    activityType: String
    yearOfAttendingActivity: Int
    type: Int

    updated: Date
    owner: Int
}