type GqlResponse {
    message: String
}

input StudentForm {
    studentId: String!
    title: String
    authors: String
    translatedAuthors: String
    startPage: String
    endPage: String
    articleNumber: String
    doi: String
    conferenceTitle: String
    hierarchyDomains: String
    internationalMagazine: String
    BDI: String
    bdiType: String
    nonBDI: String
    thesisType: String
    doctoralThesisType: String
    national: String
    international: String
    bdiDatabase: String
    cncsRecognition: String
    quality: String
    manifestationClassification: String
    manifestationType: String
    magazineType: String
    link: String
    year: String
    volume: String
    number: String
    magazineName: String
    magazineISI: String
    bookTitle: String
    bookPages: String
    edition: String
    isbn: String
    observations: String
    chapterName: String
    qualityStandard: String
    country: String
    translatedChapters: String
    manifestationName: String
    cbi: String
    patentNumber: String
    authority: String
    contactName: String
    projectCode: String
    financier: String
    function: String
    sourceTitle: String
    issue: String
    citations: String
    yearOfAward: String
    name: String
    awardName: String
    awardOrganization: String
    yearOfActivity: String
    admissionYear: String
    academyName: String
    memberType: String
    committeeName: String
    committeeYear: String
    place: String
    contact: String
    date: String
    startDate: String
    endDate: String
}
